### ISSUE TITLE
Mails are getting send without payment done

### ISSUE THREAD

**Issue by myselfgaurav** [razorpay/razorpay-magento#375]
I am using 2.8.4-beta - we are having issue , customer are getting mail even if they have not paid for order , pls fix

**Comment by enishant** [comment]
@myselfgaurav You are using plugin with an older version, this issue has been fixed in `beta-3.5.1` version. You can setup updated version of Razorpay Magento which is [3.8.5-beta](https://github.com/razorpay/razorpay-magento/releases/tag/3.8.5-beta)

You can refer to our integration documentation at https://razorpay.com/docs/payments/payment-gateway/ecommerce-plugins/magento/

**Comment by myselfgaurav** [comment]
getting below error in 3.8.5-beta


PHP Fatal error:  Uncaught Error: Class 'WpOrg\Requests\Autoload' not found in /app/code/Razorpay/Razorpay/Razorpay.php:11
Stack trace:

**Comment by enishant** [comment]
@myselfgaurav Please setup latest version [3.8.5-beta](https://github.com/razorpay/razorpay-magento/releases/tag/3.8.5-beta), this version has fixes to all known issues.

**Comment by myselfgaurav** [comment]
i am using 3.8.5-beta, when i run se:up command it gives me  below error :

PHP Fatal error: Uncaught Error: Class 'WpOrg\Requests\Autoload' not found in /app/code/Razorpay/Razorpay/Razorpay.php:11

**Comment by enishant** [comment]
@myselfgaurav Please install the extension through composer package manager.

`composer require razorpay/magento:3.8.5-beta`

Execute following commands from Magento root directory:
`bin/magento module:enable Razorpay_Magento`
`bin/magento setup:di:compile`
`bin/magento setup:upgrade`
`bin/magento cache:flush`

Install Magento Cron
`bin/magento cron:install`
