### ISSUE TITLE
Support USD as a base currency

### ISSUE THREAD

**Issue by Mayur-Wadpalliwar** [razorpay/razorpay-magento#90]
We need USD support in base currency and should convert in to INR if base_currency is anything other than INR.

Ref: 111023

**Comment by devendrabhandari** [comment]
any update?

**Comment by purpletreesoft** [comment]
We also need this. We have all products in USD on our website. When we pass USD to your gateway, it treats it as international payment, even though the billing address of the customer is india based. 
Due to this, net banking etc are not shown as it is treated as international payment.
This should not happen. 
Can you do the needful here?
